import { defineConfig } from "@github-actions-workflow-ts/cli";

export default defineConfig({
  refs: false,
  // Written for the ADOPTER, who reads this file in their own repository. They
  // have no `src/` and no `synth` script, so naming either would send them after
  // something that does not exist there. Contributors to this repository find the
  // regeneration command in CONTRIBUTING.md instead.
  // Says where to go, not only what not to touch. Someone opening this file
  // usually wants to change what CI runs, and the old header answered that with
  // "don't", which leaves editing here as the only idea they have. Under Atoma
  // the build steps are commands in config.yaml -- a file they own, that an agent
  // can write, and that survives an upgrade -- so the header names it.
  headerText: [
    "# AUTO-GENERATED by Atoma Autonomous Delivery -- DO NOT EDIT DIRECTLY.",
    "# Generated from: <source-file-path>",
    "# Edits here are lost when this file is regenerated upstream.",
    "#",
    "# To change what CI or deployment DOES, you do not need this file: put the",
    "# commands in .github/atoma/config.yaml under `checks.atoma_runs.commands` or",
    "# `deploy.atoma_runs.targets`. That file is yours, it survives upgrades, and an",
    "# agent can write it -- GitHub refuses to let one write a workflow.",
    "# See docs/customization.md, \"Set up CI and deployment\".",
    "#",
    "# Upstream: https://github.com/yuma-seno/atomaton",
    "",
  ],
  dumpOptions: {
    lineWidth: -1,
    styles: {
      "!!str": "literal",
    },
  },
  outputPaths: {
    workflows: {
      // All *.wac.ts files are the Atoma deliverable, copied into a user's
      // own .github/ -- this repo's own CI (.github/workflows/ci.yml) is
      // hand-written YAML, not generated, so no override is needed here.
      default: "dist/.github/workflows",
    },
  },
});

